# Generated by Django 3.2.9 on 2022-01-04 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20220104_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='subject',
        ),
    ]
