# Generated by Django 3.2.9 on 2022-01-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_listing_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
