# Generated by Django 3.2.9 on 2022-01-04 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_listing_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='duration',
        ),
    ]
